In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
a_tensor = torch.randn(3, 4, 5)
a_tensor

tensor([[[ 0.4114,  0.3985, -0.1746,  0.2048,  0.7100],
         [ 1.5471,  0.5832,  0.9525,  1.0934,  0.1239],
         [ 0.7198,  0.3847, -1.7822, -0.5244, -0.8916],
         [-0.4233, -0.4973, -1.1038,  0.2229,  0.8947]],

        [[-0.0557,  0.4274,  0.4708, -0.3246,  1.4481],
         [-0.5769,  0.6451, -0.1725, -0.6387, -0.7197],
         [ 0.3338, -0.7413,  1.0715, -0.9079,  0.8289],
         [ 0.8650,  2.7678, -0.8161, -0.6561, -0.6240]],

        [[ 1.1296,  0.7324, -0.8062, -1.7330, -0.5315],
         [ 1.0568, -2.0515,  1.0531, -0.9212,  0.1874],
         [-1.5953,  0.6100,  0.2121, -0.8581,  1.8864],
         [ 0.6385,  1.1398, -1.0809,  0.9911, -1.1394]]])

In [3]:
# Выведите его форму (shape)
a_tensor.shape

torch.Size([3, 4, 5])

In [6]:
# Приведите его к форме 6 X 10
a_tensor = a_tensor.reshape((6,10))
print(a_tensor)
print(a_tensor.shape)

tensor([[ 0.4114,  0.3985, -0.1746,  0.2048,  0.7100,  1.5471,  0.5832,  0.9525,
          1.0934,  0.1239],
        [ 0.7198,  0.3847, -1.7822, -0.5244, -0.8916, -0.4233, -0.4973, -1.1038,
          0.2229,  0.8947],
        [-0.0557,  0.4274,  0.4708, -0.3246,  1.4481, -0.5769,  0.6451, -0.1725,
         -0.6387, -0.7197],
        [ 0.3338, -0.7413,  1.0715, -0.9079,  0.8289,  0.8650,  2.7678, -0.8161,
         -0.6561, -0.6240],
        [ 1.1296,  0.7324, -0.8062, -1.7330, -0.5315,  1.0568, -2.0515,  1.0531,
         -0.9212,  0.1874],
        [-1.5953,  0.6100,  0.2121, -0.8581,  1.8864,  0.6385,  1.1398, -1.0809,
          0.9911, -1.1394]])
torch.Size([6, 10])


In [10]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
b_vector = torch.tensor([1, 4, 2, 2, 1, 1, 4, 2, 2, 1])
res = a_tensor.multiply(b_vector)
res

tensor([[ 0.4114,  1.5939, -0.3491,  0.4097,  0.7100,  1.5471,  2.3328,  1.9051,
          2.1868,  0.1239],
        [ 0.7198,  1.5386, -3.5644, -1.0488, -0.8916, -0.4233, -1.9893, -2.2076,
          0.4459,  0.8947],
        [-0.0557,  1.7098,  0.9417, -0.6492,  1.4481, -0.5769,  2.5804, -0.3451,
         -1.2773, -0.7197],
        [ 0.3338, -2.9653,  2.1429, -1.8158,  0.8289,  0.8650, 11.0713, -1.6322,
         -1.3122, -0.6240],
        [ 1.1296,  2.9296, -1.6123, -3.4660, -0.5315,  1.0568, -8.2060,  2.1062,
         -1.8424,  0.1874],
        [-1.5953,  2.4401,  0.4243, -1.7163,  1.8864,  0.6385,  4.5591, -2.1619,
          1.9821, -1.1394]])

In [19]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
matrix_result = res.matmul(res.t())

print(matrix_result)
print(matrix_result.shape)

tensor([[ 19.7661,  -5.4848,   4.7229,  15.6165, -13.6016,  15.4194],
        [ -5.4848,  27.4948,  -6.7166, -30.7252,  25.7498,  -3.4904],
        [  4.7229,  -6.7166,  15.5912,  30.0659, -15.3844,  18.9360],
        [ 15.6165, -30.7252,  30.0659, 145.5779, -96.9865,  50.4867],
        [-13.6016,  25.7498, -15.3844, -96.9865, 101.0752, -35.5471],
        [ 15.4194,  -3.4904,  18.9360,  50.4867, -35.5471,  46.2766]])
torch.Size([6, 6])


In [20]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x ** 3 + z - 75 * t
y.backward()

print('d(y)/d(x) =', x.grad.item())
print('d(y)/d(z) =', z.grad.item())
print('d(y)/d(t) =', t.grad.item())

d(y)/d(x) = 3.0
d(y)/d(z) = 1.0
d(y)/d(t) = -75.0


In [21]:
# Создайте единичный тензор размера 5x6
tensor = torch.eye(5, 6)
print(tensor)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])


In [22]:
# Переведите его в формат numpy
numpy_array = tensor.numpy()
print(numpy_array)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [43]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
from torch.autograd import Variable

# Задаем параметры функции
w1 = 5
x = Variable(torch.Tensor([2]), requires_grad=True)

# Определяем функцию и градиент
def function(x, w1):
    return x**w1 - 2 * x**2 + 5

def gradient(x):
    return torch.autograd.grad(function(x, w1), x)[0]

# Задаем параметры оптимизации
learning_rate = 0.01
num_iterations = 20

# Применяем градиентный спуск
for i in range(num_iterations):
    x_grad = gradient(x)
    x.data -= learning_rate * x_grad
    print("Iteration {}, x = {:.2f}, y = {:.2f}".format(i+1, x.data[0], function(x.data[0], w1)))


Iteration 1, x = 1.28, y = 5.16
Iteration 2, x = 1.20, y = 4.59
Iteration 3, x = 1.14, y = 4.33
Iteration 4, x = 1.10, y = 4.20
Iteration 5, x = 1.07, y = 4.12
Iteration 6, x = 1.05, y = 4.07
Iteration 7, x = 1.03, y = 4.04
Iteration 8, x = 1.02, y = 4.02
Iteration 9, x = 1.00, y = 4.00
Iteration 10, x = 0.99, y = 3.99
Iteration 11, x = 0.98, y = 3.99
Iteration 12, x = 0.98, y = 3.98
Iteration 13, x = 0.97, y = 3.98
Iteration 14, x = 0.96, y = 3.97
Iteration 15, x = 0.96, y = 3.97
Iteration 16, x = 0.96, y = 3.97
Iteration 17, x = 0.95, y = 3.97
Iteration 18, x = 0.95, y = 3.97
Iteration 19, x = 0.95, y = 3.97
Iteration 20, x = 0.94, y = 3.97
